language: php

php:
    - 7.1
    - 7.0
    - 5.6

cache:
    directories:
        - vendor

before_install:
    - phpenv config-rm xdebug.ini || true
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
    - composer update --prefer-dist

script:
    - composer validate --strict

    - vendor/bin/phpspec run --format dot -vvv --no-interaction
